### ISSUE TITLE
support

### ISSUE THREAD

**Issue by davehun** [DaveThw/rpi-energenie#4]
will this work with Energenie MIHO002

**Comment by davehun** [comment]
hmm scratch that they are 433

**Comment by DaveThw** [comment]
Currently, no, this code doesn't work with the Energenie MIHO002 - however I intend to add support in the future, and if I know there's some interest out there then that might help motivate me to do some more work on it!..

**Comment by DaveThw** [comment]
(although, as I think you've spotted, I don't think you'll be able to use MIHO002 sockets with the ENER314 "PiMote transmitter" plug in board for the Raspberry Pi.  I think you'll need to use the ENER314-RT "Two-way Pi-mote" plug in board instead, but I'll know more after I've had a bit of a play!..)
